platform :ios, '16.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'BLELockApp' do
  # Pods for BLELockApp
  use_frameworks!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  # BLE Manager dependency
  pod 'RNBleManager', :path => '../node_modules/react-native-ble-manager'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
